import type { Metadata } from "next";
import { Inclusive_Sans } from "next/font/google"
import "./globals.css";
import { Header } from "@/components/Header";
import { NavBar } from "@/components/Navbar";

const inclisive_sans = Inclusive_Sans({
    subsets: ['latin'],
    weight: ['400'],
})

export const metadata: Metadata = {
    title: "EasyBar -WEB",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="pt-br">
            <body
                className={`${inclisive_sans.className} h-screen`}
                style={{ display: 'grid', gridTemplateRows: '80px 1fr' }}
            >
                <Header />
                <div
                    style={{ display: 'grid', gridTemplateColumns: '140px 1fr' }}
                >
                    <NavBar />
                    {children}
                </div>
            </body>
        </html>
    );
}
