// layout.tsx
"use client"; // Adiciona essa linha no topo

import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import type { Metadata } from "next";
import { Inclusive_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { NavBar } from "@/components/Navbar";
import DashBoard from './(pages)/dashboard/page';
import FormCadastro from '@/components/cadastros';

const inclisive_sans = Inclusive_Sans({
    subsets: ['latin'],
    weight: ['400'],
});

// export const metadata: Metadata = {
//     title: "EasyBar -WEB",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="pt-br">
            <body
                className={`${inclisive_sans.className} h-screen`}
                style={{ display: 'grid', gridTemplateRows: '80px 1fr' }}
            >
                <Header />
                <div
                    style={{ display: 'grid', gridTemplateColumns: '140px 1fr' }}
                >
                    <Router>
                        <NavBar />
                        <Routes>
                            <Route path="/" element={<div>{children}</div>} />
                            <Route path="/dashboard" element={<DashBoard />} />
                            <Route path="/cadastros" element={<FormCadastro />} />
                            {/* Adicione mais rotas conforme necessário */}
                        </Routes>
                    </Router>
                </div>
            </body>
        </html>
    );
}
